### ISSUE TITLE
How to use with Cosmos DB Table API

### ISSUE THREAD

**Issue by AVOlight** [dgkanatsios/AzureServicesForUnity#8]
Can I use this SDK to access the Cosmos DB Table API?
This should work, even though I haven't tested it yet. Raise an Issue if it doesn't work for you!

Hi,
Please tell me how
I can't find any info on a REST API for Cosmos DB Tables

also tried going the experimental .NET 4.6 route by importing all the dependencies for
Microsoft.Azure.CosmosDB.Table.dll
[https://docs.microsoft.com/en-us/sandbox/gamedev/unity/azure-mobile-apps-unity](https://docs.microsoft.com/en-us/sandbox/gamedev/unity/azure-mobile-apps-unity)
but i run into this [https://forum.unity.com/threads/net-4-6-and-azure-documentdb.484988/](https://forum.unity.com/threads/net-4-6-and-azure-documentdb.484988/)

**Comment by dgkanatsios** [comment]
Hi there and thanks for trying the library.
What I mean is that you should get the CosmosDB Table Storage endpoint from the Azure portal and use the library in this GitHub repo to access it. Check [here](https://docs.microsoft.com/en-us/azure/cosmos-db/create-table-dotnet#update-your-connection-string) on how to get the endpoint/connection string for the Table Storage. Let me know if this works.

**Comment by AVOlight** [comment]
Hey, thanks for the quick reply :)
i don't understand where i should use the connection string
it includes account name, account key, endpoint, and some other stuff

SetAccountName(string accountName) just sets this Url field
Url = string.Format("https://{0}.table.cosmosdb.azure.com/", accountName);

**Comment by dgkanatsios** [comment]
You're right, I have to update the documentation if this works for you! So, give it a shot and modify these two files
- Change [this line](https://github.com/dgkanatsios/AzureServicesForUnity/blob/master/Assets/AzureServicesForUnity/Storage/TableStorageClient.cs#L19) to write
```csharp
Url = string.Format("https://{0}.table.cosmosdb.azure.com/", accountName);
```
since you'll be using the CosmosDB Table endpoint
- Modify [line 22](https://github.com/dgkanatsios/AzureServicesForUnity/blob/master/Assets/AzureServicesForUnity/_Demo%20Scenes/StorageUIScript.cs#L22) to your Account name (from the [Azure Portal](https://docs.microsoft.com/en-us/azure/cosmos-db/create-table-dotnet#update-your-connection-string)), comment the SASToken line and, finally, uncomment the AuthenticationToken line passing in your Account Key (from the [Azure Portal](https://docs.microsoft.com/en-us/azure/cosmos-db/create-table-dotnet#update-your-connection-string) again).

If this does not work too, I'll give it a shot myself. Thanks!

**Comment by AVOlight** [comment]
Thank You 👍 It's working :)

noticed this in the console: "You're using Shared Key authentication. You're highly encouraged to switch to SAS authentication"

is there a way to do this with a SASToken?

**Comment by dgkanatsios** [comment]
Awesome, thanks for trying it! Just opened [this](https://github.com/dgkanatsios/AzureServicesForUnity/issues/9) issue to update the documentation. 
To your question, no, I'm not aware of a way to use a SASToken for authentication on CosmosDB Table Storage API, so I'll fix that on the documentation update.
Regarding the SDK update, would an enumeration work for you? E.g. would code like this

```csharp
TableStorageClient.Instance.EndpointStorageType = TableStorageEndpoint.ClassicTableStorage; //or TableStorageEndpoint.CosmosDBTableStorageAPI
```
work for you? Based on the selected enumeration, the code would use the proper URL plus issue the relevant warnings (like the SAS one you encountered yourself). Thanks for your time!

**Comment by AVOlight** [comment]
Yes looks good
Thank you!
been trying to decide on a db for some time, so very happy to find this solution :)
Cheers

**Comment by dgkanatsios** [comment]
Good to know! Just pushed a [small update](https://github.com/dgkanatsios/AzureServicesForUnity/commit/8988f086572cf01f8cd42471c4cb29d76945ee91) with the code I wrote before, I'd appreciate it if you took a look and let me know if it's clearer now (added a bunch of comments in the code)

**Comment by AVOlight** [comment]
much clearer

just this 
//TableStorage.Instance.AuthenticationToken = "";
//TableStorageClient.Instance.AuthenticationToken = "";
and
Url = string.Format("https://{0}.table.cosmosdbazure.com/", accountName);
Url = string.Format("https://{0}.table.cosmosdb.azure.com/", accountName);

**Comment by dgkanatsios** [comment]
Ah, oversight, thanks! Do you want to do a Pull Request yourself? I’d love to help you with that!

**Comment by AVOlight** [comment]
thanks i haven't tried doing one of those
but i'v already been playing around with the scripts

do you know if there's a way to do transactions? (what they call them in [firebase](https://firebase.google.com/docs/firestore/manage-data/transactions))
a single call to add/update/delete data based on the condition of the current data in the database

e.g. adding 1 to a counter if the count meets condition (and waiting to run if the data is being modified)

**Comment by dgkanatsios** [comment]
Regarding atomicity/concurrency, you can read around about Table Storage in general [here](https://azure.microsoft.com/en-us/blog/managing-concurrency-in-microsoft-azure-storage-2/). I suppose the general terms of this will also apply to CosmosDB Table API. I also know that CosmosDB operations are atomic, in general but you can read the FAQ and check with the team [here](https://docs.microsoft.com/en-us/azure/cosmos-db/faq). Since you're playing with CosmosDB, you might want to check another project of mine [here](https://github.com/dgkanatsios/AzureFunctionsNodeLeaderboards-Cosmos). Again, thanks very much for your time!
